### ISSUE TITLE
Documentation and Getting Started Guide has invalid links

### ISSUE THREAD

**Issue by alexmuzenhardt** [jansc/tmjs#3]
### **Problem:**
The documentation links are not working anymore. For example "Getting Started".

### **Solution:**
It would be awesome if you could provide a valid link to follow along the documentation guide.

Thank you.

**Comment by jansc** [comment]
I've updated the links, github has changed the address of wiki links. But keep in mind that this project is deprecated. I've not done any work for 10 years, so I'm not sure if the code still works.

**Comment by alexmuzenhardt** [comment]
Thank you for your time and info :)
